import numpy as np
import cv2

def click_event(event,x,y,flags,param):
    if event==cv2.EVENT_LBUTTONDOWN:
        print(x,"  ",y)
        font=cv2.FONT_HERSHEY_SIMPLEX
        text="("+str(x)+","+str(y)+")"
        cv2.putText(img,text,(x,y),font,0.5,(255,255,255),2)
        cv2.imshow("sam",img)
    if event == cv2.EVENT_RBUTTONDOWN:
        blue=img[y,x,0]   #channel of blue is 0,green is 1,red is 2 so this will save their respective index
        green=img[y,x,1]
        red=img[y,x,2]
        font = cv2.FONT_HERSHEY_SIMPLEX
        text = "(" + str(blue) + "," + str(green) + ","+str(red)+")"
        cv2.putText(img, text, (x, y), font, 0.5, (0,0,0), 2)
        cv2.imshow("sam", img)

img=cv2.imread("lena.jpg",1)   #i have taken lena.jpg to differentiate the BGR index at different cordinates
#img=np.zeros((600,600,3),np.uint8)  here u can also use image array generated by numpy library
cv2.imshow("sam",img)

cv2.setMouseCallback("sam",click_event)
cv2.waitKey(0)
cv2.destroyAllWindows()
